### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by aschrijver** [weathermen/soundstorm#21]
Hi! Looks like you have a fairly complete AP implementation here. I was looking to add the project to the [Feneas AP watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps), but that depends on project status.

Is the project still alive? (If not I might still add to the "It's dead, Jim" section of the list).

**Comment by tubbo** [comment]
It's dead, Jim :) Sorry I didn't see this last year, I was pretty much not looking at GitHub at all since I had been furloughed from my job. Nowadays I'm kinda busy with other stuff so I haven't had time to work on it. As far as I know it works, but I haven't been able to test it with anyone else yet so I'm not 100% on that.

Maybe more like "it's not dead, it just smells funny". I'd like to get back to it someday but I don't have the time right now.

**Comment by aschrijver** [comment]
Thank you for the info! I have [updated the entry](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps#media-hosting-apps), but  not moved to the "dead" section. In any case we gave the watchlist a little twist and keep inactive projects in their category, as they are used by other devs to learn from. I hope someday you or someone else will pick up on the project.
